version: '3'

services:
  frontend:
    build: .
    ports:
      - "3201:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: multi-inference-backend:v1
    ports:
      - "8000:8000"
    volumes:
      - /Users/crescent/Multi_Inference_Backend:/app/
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 